site_name: "💾 Disruptive Architectures: IOT, Big Data e IA 💾"

theme: material

nav:
  - "Programação de Aulas": index.md
  - "Calendário": calendario.md
  - "Fundamentos e Ferramentas de Big Data": "fundbig.md"
  - "Processamento de Dados com Apache Spark": spark.md
  - "Projetos Práticos de Big Data": probig.md
  - "Pipeline de Dados como Arquitetura Medalhão e Firebase": pipefirebase.md